apiVersion: v1
kind: Service
metadata:
  name: java-backend
  labels:
    app: java-backend
spec:
  type: ClusterIP
  selector:
    app: java-backend
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090